name: init-job
inputs:
  no-checkout:
    description: 'if action should not checkout'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      if: ${{ inputs.checkout }}
    - uses: actions/setup-node@v3
      with:
        node-version: '16.10.0'
        cache: 'npm'
    - uses: actions/cache@v2
      id: cache
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - run: npm ci --ignore-scripts
      if: steps.cache.outputs.cache-hit != 'true'
