name: get-affected-test
on:
  # run on push
  push:
    branches:
      - '**'

jobs:
  gen-affected:
    timeout-minutes: 5
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    outputs:
      AFFECTED: ${{ steps.gen-affected.outputs.AFFECTED }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
          fetch-depth: 0
      - uses: ./.github/actions/init-job
      - run: |
          AFFECTED=$(npm run get:affected)
          echo $AFFECTED
          echo ":set-output name=AFFECTED::$AFFECTED"

  print-affected:
    timeout-minutes: 5
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    steps:
      - run: echo ${{ needs.gen-affected.outputs.AFFECTED }}
      - run: echo ${{ contains(fromJSON(needs.gen-affected.outputs.AFFECTED), 'common-react') }}
