name: on-push
on:
  # run on push
  push:
    branches:
      - '**'

jobs:
  gen-affected:
    timeout-minutes: 5
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    outputs:
      AFFECTED: ${{ steps.gen-affected.outputs.AFFECTED }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
          fetch-depth: 0
      - uses: ./.github/actions/init-job
      - run: |
          AFFECTED_LINT=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project --target=lint)
          AFFECTED_TEST=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project --target=test)
          AFFECTED_BUILD=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project --target=build)
          AFFECTED_LIGHTHOUSE=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project --target=lighthouse)
          AFFECTED="$AFFECTED_LINT $AFFECTED_TEST $AFFECTED_BUILD $AFFECTED_LIGHTHOUSE"
          echo $AFFECTED
          echo "::set-output name=AFFECTED:\"$AFFECTED\""
          echo test1: ${{ contains(needs.gen-affected.outputs.AFFECTED, 'internal-client') }}
          echo test2: ${{ contains('internal-client, internal-client-e2e internal-client internal-client ', 'internal-client') }}

  internal-client:
    timeout-minutes: 5
    # TODO: update to always run, exists only as a sanity test
    if: "!contains(github.event.head_commit.message, 'skip ci') && contains(needs.gen-affected.outputs.AFFECTED, 'internal-client')"
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/init-job
      - run: npx nx internal-client:lint
      - run: npx nx internal-client:test
      - run: npx nx internal-client:build
      # - Add lighthouse
      # - Add cache for gh-pages deployment

    # - storybook
    # - doc generation
    # - Gen graph
