name: on-push
on:
  # run on push
  push:
    branches:
      - '**'

jobs:
  gen-affected:
    timeout-minutes: 5
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    outputs:
      AFFECTED: ${{ steps.gen-affected.outputs.AFFECTED }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
          fetch-depth: 0
      - uses: ./.github/actions/init-job
      - run: |
          AFFECTED=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project)
          echo $AFFECTED
          echo "::set-output name=AFFECTED:$AFFECTED"

  internal-client:
    timeout-minutes: 5
    # TODO: update to always run, exists only as a sanity test
    if: "!contains(github.event.head_commit.message, 'skip ci') && contains(needs.gen-affected.outputs.AFFECTED, 'internal-client')"
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/init-job
      - run: npx nx internal-client:lint
      - run: npx nx internal-client:test
      - run: npx nx internal-client:build
      # - Add lighthouse
      # - Add cache for gh-pages deployment

    # - storybook
    # - doc generation
    # - Gen graph
