name: on-push
on:
  # run on push
  push:
    branches:
      - '**'

jobs:
  gen-affected:
    timeout-minutes: 5
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    outputs:
      AFFECTED: ${{ steps.gen-affected.outputs.AFFECTED }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
          fetch-depth: 0
      - uses: ./.github/actions/init-job
      - id: gen-affected
        run: |
          AFFECTED_LINT=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project --target=lint)
          AFFECTED_TEST=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project --target=test)
          AFFECTED_BUILD=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project --target=build)
          AFFECTED_LIGHTHOUSE=$(npx nx print-affected --base=origin/main --head=$GITHUB_REF --select=tasks.target.project --target=lighthouse)
          AFFECTED="$AFFECTED_LINT $AFFECTED_TEST $AFFECTED_BUILD $AFFECTED_LIGHTHOUSE"
          echo $AFFECTED
          echo "::set-output name=AFFECTED::$AFFECTED"

  internal-client:
    timeout-minutes: 5
    # TODO: update to always run, exists only as a sanity test
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && contains(needs.gen-affected.outputs.AFFECTED, 'internal-client') }}
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/init-job
      - run: npx nx run internal-client:lint
      - run: npx nx run internal-client:test
      - run: npx nx run internal-client:build
      # - Add lighthouse
      # - Add cache for gh-pages deployment

  # Job that generates the storybook configuration for all projects that have it,
  # where the storybook library will be built and manage ALL the projects.
  # together via composition. Or at least thats the plan.
  # All of these together will be deployed within the gh-page job.
  storybook:
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && needs.gen-affected.outputs.AFFECTED != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/init-job
      - run: npx nx run-many --target=build-storybook --all
      # - Add cache for gh-pages deployment

    # - doc generation
    # - Gen graph
    # - gh-page job
